### ISSUE TITLE
Use import()

### ISSUE THREAD

**Issue by bondz** [notgiorgi/react-router-partial-app-loading#1]
Webpack 2 advices using import() over System.import() would you consider changing, and using that instead?

**Comment by notgiorgi** [comment]
Can you provide link referencing that advice?

**Comment by bondz** [comment]
[webpack 2 beta release](https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.28)

**Comment by notgiorgi** [comment]
@bondz Good point, I'll try to fix this as soon as possible.
I'd welcome pull request too.

**Comment by bondz** [comment]
Any particular reason why you importing and exporting modules aren't consistent? The `module.exports = ` could be `export default`

That said, looks like replacing System.import with the import operator should be easy, take `profile.js`

```js
module.exports = {
  path: 'profile',
  getComponent(nextState, cb) {
    System
    .import('./components/Profile')
    .then(component => cb(null, component))
    .catch(err => cb(err))
  }
}
```

should be 

```js
export default {
  path: 'profile',
  getComponent(nextState, cb) {
    import('./components/Profile')
    .then(({default: component}) => cb(null, component))
    .catch(err => cb(err))
  }
}
```

**Comment by notgiorgi** [comment]
As readme says, I forked the repo from `react-router/examples/huge-apps` example, which used `module.exports`.

For first few commits my goal was to replace webpack 1 style `require.ensure` with webpack 2 `import`.

Those final touches you're suggesting are great and will be done 🤓
